### ISSUE TITLE
Email de convite na caixa de spam

### ISSUE THREAD

**Issue by tapajos** [rpanachi/mooney.rb#10]
O email de convite está caindo na caixa de spam.

**Comment by rpanachi** [comment]
tapajos, os emails estão sendo enviados temporariamente por uma conta do Gmail... alguma sugestão para resolver isso?

**Comment by tapajos** [comment]
É Google Apps? Se for dá uma conferida no DNS. Existem algumas configurações recomendadas pelo gmail.
