### ISSUE TITLE
Possibilitar inclusao de credito parcelado

### ISSUE THREAD

**Issue by ihercowitz** [rpanachi/mooney.rb#12]
No cadastramento de contas do cartao de crédito seria interessante a possibilidade de incluir o credito parcelado, talvez com uma checkbox onde se pudesse informar que é um credito parcelado e em quantas vezes sera pago. Com isso essa data e valor seriam colocados em todos os meses correspondentes a parcela.

**Comment by pbalduino** [comment]
https://www.pivotaltracker.com/story/show/11939411
