### ISSUE TITLE
Certificado

### ISSUE THREAD

**Issue by tapajos** [rpanachi/mooney.rb#8]
O certificado SSL não é válido.

**Comment by tapajos** [comment]
Esse certificado se refere ao sistema no ar em: https://mooney.1up4dev.com

**Comment by rpanachi** [comment]
tapajos, alguma idéia de como resolver isso com um certificado auto assinado?

**Comment by tapajos** [comment]
Não rola.

**Comment by pbalduino** [comment]
https://www.pivotaltracker.com/story/show/11938963
